### ISSUE TITLE
Question concerning podman on Android system? 

### ISSUE THREAD

**Issue by Yuiry-IV** [Poorunga/websocket_echo#4]
Hello @Poorunga 

As  I understand from your message in [this](https://github.com/containers/podman/issues/5836#issuecomment-614797811) thread: You've been reach success in running podman in Android. 
I'm trying to run [mgoltzsche/podman-static](https://github.com/mgoltzsche/podman-static) on Android 12. I've tried several options, but all failed:

1. rootless: `podman run quay.io/podman/hello` -> 
```Error: checking slirp4netns binary /data/local/tmp/podman-linux-arm64/usr/local/bin/: "slirp4netns \"\": fork/exec /data/local/tmp/podman-linux-arm64/usr/local/bin/: permission denied": slirp4netns "": fork/exec /data/local/tmp/podman-linux-arm64/usr/local/bin/: permission denied```
2. rootless:  `podman run --network=none quay.io/podman/hello` ->
```Error: OCI runtime error: runc: runc create failed: unable to start container process: unable to setup user: invalid argument```

At same time:
- `slirp4netns -v` ->
```
slirp4netns version 1.2.0
commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
libslirp: 4.7.0
SLIRP_CONFIG_VERSION_MAX: 4
libseccomp: 2.5.4
```

- `runc -v` ->
```runc version 1.1.7
commit: v1.1.7-0-g860f061
spec: 1.0.2-dev
go: go1.18.10
libseccomp: 2.5.4
```
3. Rootfull mode also failed `podman run quay.io/podman/hello`: 
```Error: OCI runtime error: time="2023-08-11T17:16:07Z" level=error msg="mkdir /run: read-only file system"
```

Can you give me a hint how to run it successful ?

**Comment by Poorunga** [comment]
@Yuiry-IV Sorry, I don't have any ideas on this question. Maybe it's a linux permission issue?

**Comment by Yuiry-IV** [comment]
Hello @Poorunga, 

Thank you for response. For now have not idea. Will continue investigation
